// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwzlgevdcplryjygfsdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3emxnZXZkY3BscnlqeWdmc2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5NzE2NDAsImV4cCI6MjA3OTU0NzY0MH0.xobOECK5Rr0eQ0kGEEgS6aFT0vQBwg6EYYuE-B9Ozts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});